DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGSERIAL PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGSERIAL PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
    ID BIGSERIAL PRIMARY KEY,
    AUTHORID BIGINT,
    GENREID BIGINT,
    NAME VARCHAR(255),
    FOREIGN KEY (AUTHORID) references AUTHOR(ID),
    FOREIGN KEY (GENREID) references GENRE(ID));
