logging:
  level:
    root: ERROR

server:
  port: 8080

spring:

  shell:
    interactive:
      enabled: true

  main:
    allow-circular-references: true


  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

