logging:
  level:
    root: ERROR

server:
  port: 8080

spring:
  messages:
    encoding: UTF-8
  main:
    allow-circular-references: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
