spring:
  main:
    allow-circular-references: true

  batch:
    job:
      enabled: true

#  shell:
#    interactive:
#      enabled: true
#    noninteractive:
#      enabled: false
#    command:
#      version:
#        enabled: true

  mongodb:
    embedded:
      version: 3.4.0

  data:
    mongodb:
      host: localhost
      port: 0
      database: library

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    ROOT: INFO
